config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated do
      root to: 'home#index'
    end

    unauthenticated do
      root to: 'devise/sessions#new'
    end
  end

  resources :stores
  resources :pets
  resources :supplies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :store
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :pets
  has_many :supplies
end

app/models/supply.rb
class Supply < ApplicationRecord
  belongs_to :store
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  def index
    @pets = Pet.all
    if params[:species].present?
      @pets = @pets.where(species: params[:species])
    end
  end

  def show
    @pet = Pet.find params[:id]
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new pet_params
    if @pet.save
      redirect_to @pet, notice: 'Pet was successfully created.'
    else
      render :new
    end
  end

  def edit
    @pet = Pet.find params[:id]
  end

  def update
    @pet = Pet.find params[:id]
    if @pet.update pet_params
      redirect_to @pet, notice: 'Pet was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @pet = Pet.find params[:id]
    @pet.destroy!
    redirect_to pets_path, notice: 'Pet was successfully deleted.'
  end

  private

  def pet_params
    params.require(:pet).permit :name, :species, :breed, :store_id
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController

  def index
    @stores = Store.all
  end

  def show
    @store = Store.find params[:id]
  end

  def new
    @store = Store.new
  end

  def create
    @store = Store.new store_params
    if @store.save
      redirect_to @store, notice: 'Store was successfully created.'
    else
      render :new
    end
  end

  def edit
    @store = Store.find params[:id]
  end

  def update
    @store = Store.find params[:id]
    if @store.update store_params
      redirect_to @store, notice: 'Store was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @store = Store.find params[:id]
    @store.destroy!
    redirect_to stores_path, notice: 'Store was successfully deleted.'
  end

  private

  def store_params
    params.require(:store).permit :name, :description
  end

  def store_name
    @store.show(@pet.store_id)
  end
end

app/controllers/supplies_controller.rb
class SuppliesController < ApplicationController

  def index
    @supplies = Supply.all
  end

  def show
    @supply = Supply.find params[:id]
    @supplies = Supply.all
  end

  def new
    @supply = Supply.new
  end

  def create
    @supply = Supply.new supply_params
    if @supply.save
      puts "*" * 80
      puts "GOT HERE"
      puts "*" * 80
      redirect_to supplies_path, notice: 'Supply item was successfully created.'
    else
      render :new
      puts @supply.errors.full_messages
    end
  end

  def edit
    @supply = Supply.find params[:id]
  end

  def update
    @supply = Supply.find params[:id]
    if @supply.update supply_params
      redirect_to supplies_path, notice: 'Supply item was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @supply = Supply.find params[:id]
    @supply.destroy!
    redirect_to supplies_path, notice: 'Supply item was successfully deleted.'
  end

  private

  def supply_params
    params.require(:supply).permit :name, :brand, :quantity, :store_id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
%h1.center Welcome to the Pet Store!

%img= image_tag 'main-header-cat.jpg'

app/views/layouts/_flash.haml
- if alert
  .alert
    = alert

- if notice
  .notice
    = notice

app/views/layouts/_header.haml
%header
  %div.brand-logo
    %img= link_to image_tag('logo-purple.png'), 'http://localhost:3000'
    %ul.nav.navbar
      %li
        = link_to 'Stores', stores_path
      %li
        = link_to 'Pets', pets_path
      %li
        = link_to 'Supplies', supplies_path
      %li
        .session
          - if current_user
            = link_to "Sign Out", destroy_user_session_path, method: :delete

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Pet Store

    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'

    = csrf_meta_tags

  %body
    = render 'layouts/header'
    = render 'layouts/flash'

    %main
      = yield

app/views/pets/_filter.html.haml
= link_to 'Cats', pets_path(species: "Cat")
|
= link_to 'Dogs', pets_path(species: "Dog")

app/views/pets/_form.html.haml
= simple_form_for @pet do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.input :species
    = f.input :breed

    = f.association :store

  .form-actions
    = f.button :submit

app/views/pets/edit.html.haml
%h1 Edit Pet

= render 'form'

= link_to 'Show', @pet
\|
= link_to 'Back', pets_path

app/views/pets/index.html.haml
%h1 Pets

= link_to 'Create a New Pet', new_pet_path

%h6 Filter by:
= render 'filter'

%table
  %thead
    %tr
      %th Name
      %th Species
      %th Breed
      %th

  %tbody
    - @pets.each do |pet|
      %tr
        %td= link_to pet.name, pet
        %td= pet.species
        %td= pet.breed
        %td
          = link_to 'Edit', edit_pet_path(pet)
          = link_to 'Delete', pet, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/pets/new.html.haml
%h1 New pet

= render 'form'

= link_to 'Back', pets_path

app/views/pets/show.html.haml
%h1= @pet.name
- if @pet.breed === 'American Shorthair' || @pet.breed === 'Short Hair'
  %img= image_tag "cat1.jpg"
- elsif @pet.breed === 'Scottish Fold'
  %img= image_tag "cat5.jpg"
- elsif @pet.breed === 'Long Hair'
  %img= image_tag "cat8.jpg"
- elsif @pet.breed === 'German Shepard'
  %img= image_tag "dog5.jpg"
- elsif @pet.breed === 'Pug' || @pet.breed === 'Bulldog'
  %img= image_tag "dog3.jpg"
- elsif @pet.breed === 'Chihuahua' || @pet.breed === 'Pincher'
  %img= image_tag "dog6.jpg"
- elsif @pet.breed === 'Corgi'
  %img= image_tag "dog4.jpg"
- elsif @pet.breed === 'Mut'
  %img= image_tag "dog1.jpg"

%h3 Species: #{@pet.species}
%h3 Breed: #{@pet.breed}
%h3 Store: #{@pet.store.name}


= link_to 'Edit', edit_pet_path(@pet)
\|
= link_to 'Back', pets_path

app/views/stores/_form.haml
= simple_form_for @store do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :description

  .form-actions
    = f.submit

app/views/stores/edit.html.haml
%h1 Edit Store

= render 'form'

= link_to 'Show', @store
\|
= link_to 'Back', stores_path

app/views/stores/index.html.haml
%h1 Stores

= link_to 'New Store', new_store_path

%table
  %thead
    %tr
      %th Name
      %th Description

  %tbody
    - @stores.each do |store|
      %tr
        %td= link_to store.name, store_path(store)
        %td= store.description
        %td
          = link_to 'Edit', edit_store_path(store)
          = link_to 'Delete', store_path(store), method: :delete, data: { confirm: 'Are you sure?' }

app/views/stores/new.html.haml
%h1 New Store
= render 'form'

app/views/stores/show.html.haml
%h1= @store.name

= link_to 'Edit', edit_store_path(@store)
|
= link_to 'All Stores', stores_path
%p= @store.description
%h3= 'Available Pets'
- @store.pets.each do |pet|
  %ul
    %li= link_to pet.name, pet_path(pet)
%h3= 'Available Supplies'
- @store.supplies.each do |supply|
  %ul
    %li= link_to supply.name, supplies_path(supply)

app/views/supplies/_form.html.haml
= simple_form_for @supply do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.input :brand
    = f.input :quantity

    = f.association :store

  .form-actions
    = f.button :submit

app/views/supplies/edit.html.haml
%h1 Edit Supplies

= render 'form'

= link_to 'Show', @supply
\|
= link_to 'Back', supplies_path

app/views/supplies/index.html.haml
%h1 Supplies

= link_to 'Add Suppies', new_supply_path

%table
  %thead
    %tr
      %th Name
      %th Brand
      %th Quantity
      %th Store

  %tbody
    - @supplies.each do |supply|
      %tr
        %td= supply.name
        %td= supply.brand
        %td= supply.quantity
        %td= supply.store.name
        %td
          = link_to 'Edit', edit_supply_path(supply)
          = link_to 'Delete', supply, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/supplies/new.html.haml
%h1 New supplies

= render 'form'

= link_to 'Back', supplies_path

app/views/supplies/show.html.haml
%h1= @supply.name

= link_to 'Edit', edit_supply_path(@supply)
= link_to 'All Stores', supplies_path
%h1= 'Available Supplies'
- @supplies.each do |supply|
  %ul
    %li= supply.name
    %li= supply.quantity